# EXAMPLE NGINX.CONF FILE FOR TWO SERVER AT PORT 80

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  example.com;

        location / {
            root   /var/www/example.com;
            index  index.html index.htm;
        }
    }

    server {
        listen       80;
        server_name  example2.com;

        location / {
            root   /var/www/example2.com;
            index  index.html index.htm;
        }
    }
}